app:
    resource: "@AppBundle/Controller/"
    type:     annotation

app:
    resource: "@AppBundle/Models/"
    type:     annotation

abcmy_newpage:
    pattern:  /add/{doctor}
    defaults: { _controller: AppBundle:Controller:addDoctor }